### ISSUE TITLE
Local access available?

### ISSUE THREAD

**Issue by chris24walsh** [ThibautTrarbach/daikintomqtt#8]
Would guess not, but will local access be available using this? Sorry to ask but it wasn't clear to me - but you are one of only 2 repos on Github that reference the BRP069A78 module.

**Comment by ThibautTrarbach** [comment]
Hi,

If you mean by local mode, you don't use the Daikin cloud at any time. No, unfortunately that is not possible. I rely on the daikin cloud. And in particular the Daikin Onecta APIs

**Comment by chris24walsh** [comment]
Ok, thanks for clearing that up. I have just had my Daikin Altherma installed, and want to give your project a go but could use some help understanding how to build and run it. Are you using `npm`? Not sure what commands to use (MacOS terminal)
